### PR TITLE
APPS-1737 Nextflow | Test / confirm default vs. custom applet name, title, summary, import via CLI

### PR DESCRIPTION
**Pull request by r-i-v-a**

### CODE REVIEW

**Comment by r-i-v-a** [comment]
[] Run tests [] Run tests https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/417/

**Comment by r-i-v-a** [comment]
[] Running tests https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/417/

**Comment by r-i-v-a** [comment]
[X] Ran tests 

https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/417/
https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/417/parameters/

**Review by commandlinegirl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
