### PR TITLE
APPS-1522 fix missing required inputs cmd

### PR DESCRIPTION
**Pull request by YuxinShi0423**

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]

**Comment by YuxinShi0423** [comment]
https://staging.dnanexus.com/projects/GJ839q80QpbFg9BZ1Jk5J6Yg/monitor/job/GK2k34Q0QpbGb0Gj4g1yX7JK

**Comment by commandlinegirl** [comment]
Does the integration tests (for the nf module) on Jenkins pass on this branch?

**Comment by YuxinShi0423** [comment]
https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/259/console
cc @commandlinegirl

**Review by commandlinegirl — APPROVED** [review]
Thank you!

**Pull request merged**
