### PR TITLE
APPS-1518 preserve folder structure when publishing files

### PR DESCRIPTION
**Pull request by YuxinShi0423**

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]

**Comment by YuxinShi0423** [comment]
https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/260/console

**Review by commandlinegirl — APPROVED** [review]
LGTM, modulo a comment that explains that cp is used to preserve symlinks (if that's true) or any other relevant info :) Thank you!

**Comment by YuxinShi0423** [comment]
> LGTM, modulo a comment that explains that cp is used to preserve symlinks (if that's true) or any other relevant info :) Thank you!
@commandlinegirl Here is the link to `dx-upload-all-output` which is used when uploading published files:
https://github.com/dnanexus/dx-toolkit/blob/master/src/python/scripts/dx-upload-all-outputs#L158-L161

**Review by mhrvol — COMMENTED** [review]
lgtm

**Pull request merged**
