### PR TITLE
APPS-1693 nextaur 1.6.2 and nextflow 22.10.0 update

### PR DESCRIPTION
**Pull request by mhrvol**

### CODE REVIEW

**Comment by mhrvol** [comment]
Previous master tests:
16.04 stg tests - https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-16.04-python2/

https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-20.04-python3/775/console
But the error is : 
ERROR: test_find_analyses_run_by_jobs (test_dxclient.TestDXClientFind)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dx-toolkit/src/python/test/test_dxclient.py", line 5464, in test_find_analyses_run_by_jobs
    analysis_id = dxpy.api.job_describe(job_id, {})['dependsOn'][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dx-toolkit/src/python/test/test_dxclient.py", line 5469, in test_find_analyses_run_by_jobs
    raise Exception("Timeout while waiting for workflow to be run by root execution")
Exception: Timeout while waiting for workflow to be run by root execution


Nextflow tests: https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/ on nextaur-1.6.2


QE tests on nextaur-1.6.2 : https://github.com/dnanexus/nextaur-app/actions/runs/4324827753

**Review by commandlinegirl — APPROVED** [review]
Please update Nextaur version in the applet script

**Review by commandlinegirl — CHANGES_REQUESTED** [review]
Please update the version

**Review by commandlinegirl — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
