### PR TITLE
APPS-1554 NF - fix profile overriding

### PR DESCRIPTION
**Pull request by mhrvol**

### CODE REVIEW

**Comment by mhrvol** [comment]
tests: https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/387/

**Comment by mhrvol** [comment]
Qe nextaur tests:
https://github.com/dnanexus/nextaur-app/actions/runs/4406662491

**Review by r-i-v-a — APPROVED** [review]

**Review by commandlinegirl — COMMENTED** [review]
@mhrvol The integration tests pass but they were passing before as well so maybe the profile-testing test there requires an update so that it picks up the issue you're fixing here?

**Review by commandlinegirl — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
